// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlf7Xvx4yj2tAJpA3pAyV1mpKz66T7iec',
    appId: '1:634464349649:web:02c7e04c3281a9cabc04f0',
    messagingSenderId: '634464349649',
    projectId: 'prospect-74092',
    authDomain: 'prospect-74092.firebaseapp.com',
    storageBucket: 'prospect-74092.firebasestorage.app',
    measurementId: 'G-EP59X3RVYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtO5E4vinocZfh-aTR1O21EqspXWDQWHY',
    appId: '1:634464349649:android:997d30924fa572b3bc04f0',
    messagingSenderId: '634464349649',
    projectId: 'prospect-74092',
    storageBucket: 'prospect-74092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrB916F6STnbIpdhrsZVK__hSO4EgELyQ',
    appId: '1:634464349649:ios:77c275fb0040c7bbbc04f0',
    messagingSenderId: '634464349649',
    projectId: 'prospect-74092',
    storageBucket: 'prospect-74092.firebasestorage.app',
    iosBundleId: 'com.example.prospekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrB916F6STnbIpdhrsZVK__hSO4EgELyQ',
    appId: '1:634464349649:ios:77c275fb0040c7bbbc04f0',
    messagingSenderId: '634464349649',
    projectId: 'prospect-74092',
    storageBucket: 'prospect-74092.firebasestorage.app',
    iosBundleId: 'com.example.prospekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlf7Xvx4yj2tAJpA3pAyV1mpKz66T7iec',
    appId: '1:634464349649:web:900ddee9bca8c2c8bc04f0',
    messagingSenderId: '634464349649',
    projectId: 'prospect-74092',
    authDomain: 'prospect-74092.firebaseapp.com',
    storageBucket: 'prospect-74092.firebasestorage.app',
    measurementId: 'G-ZSLNHJ0W0F',
  );

}